
pipeline:

my-build:
    privileged: true
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker build -t ramesh-hello-world .
    when:
      branch: master
      event: pushn
